name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  
  stop:
    runs-on: self-hosted
    steps:
    - name: Stop current compose containers
      run: docker-compose down

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose build
      
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Run the Docker application
      run: docker-compose up
