name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  
  stop:
    runs-on: self-hosted
    steps:
    - name: Stop current compose containers
      run: docker-compose down

  build:
    runs-on: self-hosted
    needs: stop
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose up --no-start
      
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Run the database
      run: docker-compose start db
    
    - name: Run Fast API
      run: docker-compose start api
